#!/usr/bin/env python3

import argparse
import signal
import sys
import logging
from rpi_rf_gpiod import RFDevice

# pylint: disable=unused-argument
def exithandler(signal, frame):
    sys.exit(0)

logging.basicConfig(level=logging.INFO, datefmt='%Y-%m-%d %H:%M:%S',
                    format='%(asctime)-15s - [%(levelname)s] %(module)s: %(message)s', )

parser = argparse.ArgumentParser(description='Receives a decimal code via a 433/315MHz GPIO device')
parser.add_argument('-g', dest='gpio', type=int, default=27,
                    help="GPIO pin (Default: 27)")
args = parser.parse_args()

signal.signal(signal.SIGINT, exithandler)

rfdevice = RFDevice(args.gpio)

try:
    for data in rfdevice.rx_listen():
        logging.info(str(data['code']) +
                     " [pulselength " + str(data['pulselength']) +
                     ", protocol " + str(data['protocol']) + "]")
except KeyboardInterrupt:
    logging.info("Exiting...")
    sys.exit(0)
